import { FieldTypes } from "../../Utils/staticObj";
import * as Yup from "yup";

export const TransactionFormJSON = {
  ["form-slug"]: "Transaction-form",
  formName: "Transaction ",
  formPosition: "start",
  card: {
    style: {
      background: "#121417",
      color: "#c5bdbd",
    },
    shadow: "rgba(0, 0, 0, 0.1) 0px 4px 12px",
  },
  fieldStyle: {
    background: "#83839421",
    labelColor: "white",
    color: "white",
  },
  submitButton: {
    label: "Transaction",
    position: "around",
    style: {
      background: "#00800085",
      color: "white",
      paddingLeft: "20px",
      paddingRight: "20px",
    },
  },
  resetButton: {
    required: true,
    label: "Reset",
    style: {
      background: "#d04040",
      color: "white",
      paddingLeft: "20px",
      paddingRight: "20px",
    },
  },
  Fields: [
    {
      initValue: "",
      validateField: Yup.number().required("ProcessingCode is Requird"),
      fieldType: FieldTypes.NUMBER,
      label: "Processing Code",
      placeholder: "Processing Code",
      name: "ProcessingCode",
      fildSize: {
        md: "6",
        xs: "12",
        sm: "12",
        lg: "6",
      },
    },
    {
      initValue: "",
      validateField: Yup.number().required("SystemTraceNr is Requird"),
      fieldType: FieldTypes.NUMBER,
      label: "SystemTrace Nr",
      placeholder: "SystemTrace Nr",
      name: "SystemTraceNr",
      fildSize: {
        md: "6",
        xs: "12",
        sm: "12",
        lg: "6",
      },
    },
    {
      initValue: "",
      validateField: Yup.number().required("FunctionCode is Requird"),
      fieldType: FieldTypes.NUMBER,
      label: "FunctionCode",
      placeholder: "FunctionCode",
      name: "FunctionCode",
      fildSize: {
        md: "6",
        xs: "12",
        sm: "12",
        lg: "6",
      },
    },
    {
      initValue: "",
      validateField: Yup.string().required("CardNo is Requird"),
      fieldType: FieldTypes.TEXT,
      label: "CardNo",
      placeholder: "CardNo",
      name: "CardNo",
      fildSize: {
        md: "6",
        xs: "12",
        sm: "12",
        lg: "6",
      },
    },
    {
      initValue: "",
      validateField: Yup.string().required("CardHolder is Requird"),
      fieldType: FieldTypes.TEXT,
      label: "CardHolder",
      placeholder: "CardHolder",
      name: "CardHolder",
      fildSize: {
        md: "6",
        xs: "12",
        sm: "12",
        lg: "6",
      },
    },
    {
      initValue: "",
      validateField: Yup.number().required("AmountTrxn is Requird"),
      fieldType: FieldTypes.NUMBER,
      label: "AmountTrxn",
      placeholder: "AmountTrxn",
      name: "AmountTrxn",
      fildSize: {
        md: "6",
        xs: "12",
        sm: "12",
        lg: "6",
      },
    },
    {
      initValue: "",
      validateField: Yup.number().required("CurrencyCode is Requird"),
      fieldType: FieldTypes.NUMBER,
      label: "CurrencyCode",
      placeholder: "CurrencyCode",
      name: "CurrencyCode",
      fildSize: {
        md: "6",
        xs: "12",
        sm: "12",
        lg: "6",
      },
    },
    {
      initValue: "",
      validateField: Yup.number().required("CurrencyCode is Requird"),
      fieldType: FieldTypes.NUMBER,
      label: "CurrencyCode",
      placeholder: "CurrencyCode",
      name: "CurrencyCode",
      fildSize: {
        md: "6",
        xs: "12",
        sm: "12",
        lg: "6",
      },
    },
    {
      initValue: "",
      validateField: Yup.number().required("CurrencyCode is Requird"),
      fieldType: FieldTypes.NUMBER,
      label: "CurrencyCode",
      placeholder: "CurrencyCode",
      name: "CurrencyCode",
      fildSize: {
        md: "6",
        xs: "12",
        sm: "12",
        lg: "6",
      },
    },
    {
      initValue: "",
      validateField: Yup.number().required("CurrencyCode is Requird"),
      fieldType: FieldTypes.NUMBER,
      label: "CurrencyCode",
      placeholder: "CurrencyCode",
      name: "CurrencyCode",
      fildSize: {
        md: "6",
        xs: "12",
        sm: "12",
        lg: "6",
      },
    },
    {
      initValue: "",
      validateField: Yup.number().required("CurrencyCode is Requird"),
      fieldType: FieldTypes.NUMBER,
      label: "CurrencyCode",
      placeholder: "CurrencyCode",
      name: "CurrencyCode",
      fildSize: {
        md: "6",
        xs: "12",
        sm: "12",
        lg: "6",
      },
    },
    {
      initValue: "",
      validateField: Yup.number().required("CurrencyCode is Requird"),
      fieldType: FieldTypes.NUMBER,
      label: "CurrencyCode",
      placeholder: "CurrencyCode",
      name: "CurrencyCode",
      fildSize: {
        md: "12",
        xs: "12",
        sm: "12",
        lg: "12",
      },
    },
  ],
};
